#!/usr/bin/env bash

SCRIPTPATH=$(dirname $0)

export PYTHONIOENCODING=utf-8
export GOOGLE_APPLICATION_CREDENTIALS=$SCRIPTPATH/keys/buddy-pi-key.json

source $SCRIPTPATH/env/bin/activate
python $SCRIPTPATH/buddy-pi.py
